apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    delivery-pipeline-id: actionable-iq-pipeline
    location: us-east5
    managed-by: google-cloud-deploy
    project-id: actionableiq
    target-id: frontend-prod
  name: frontend-service
spec:
  template:
    metadata: # <--- METADATA FOR THE REVISION TEMPLATE
      name: frontend-service-prod-rev-v3 # Optional: Revision name hint (make this unique, e.g., "frontend-prod-v2")
      annotations:
        run.googleapis.com/max-instances: "40" # Preferred Cloud Run way for revision max scaling
        clouddeploy.googleapis.com/prod-rollout-version: "prod-frontend-v2" # Your unique annotation
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 788583965739-compute@developer.gserviceaccount.com
      containers:
      - image: frontend-image
        env:
        # For this FIRST pass to prod, REACT_APP_API_URL should still point to STAGING backend
        - name: REACT_APP_API_URL
          value: "https://backend-service-788583965739.us-east5.run.app/api" # STAGING backend URL for now
        - name: REACT_APP_GOOGLE_CLIENT_ID
          value: "788583965739-jdtuifdn617lsh59mtg5775c4v0ms110.apps.googleusercontent.com"
        ports:
        - name: http1
          containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        startupProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 24
          tcpSocket:
            port: 80
  traffic:
  - latestRevision: true
    percent: 100