apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  # Your labels like delivery-pipeline-id, location, managed-by, project-id, target-id are good.
  # Skaffold/Cloud Deploy usually injects the release-id.
  labels:
    delivery-pipeline-id: actionable-iq-pipeline
    location: us-east5
    managed-by: google-cloud-deploy
    project-id: actionableiq
    target-id: frontend-prod
  name: frontend-service # Ensure this is the correct name of your Cloud Run service
spec:
  template:
    metadata:
      # labels:
        # Add any specific labels for the revision template itself if needed
        # run.googleapis.com/startupProbeType: Custom # This is usually set by Cloud Run based on probe presence
      annotations:
        autoscaling.knative.dev/maxScale: '40' # Keep if needed
    spec:
      containerConcurrency: 80 # Keep if needed
      timeoutSeconds: 300      # Keep if needed
      serviceAccountName: 788583965739-compute@developer.gserviceaccount.com # Verify this SA
      containers:
      - image: frontend-image # <<< SOLUTION FOR ISSUE A
        env:
        - name: REACT_APP_API_URL
          value: "https://backend-service-788583965739.us-east5.run.app/api"
        - name: REACT_APP_GOOGLE_CLIENT_ID
          value: "788583965739-jdtuifdn617lsh59mtg5775c4v0ms110.apps.googleusercontent.com"
        ports:
        - name: http1 # Knative requires the port to be named
          containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        startupProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 24
          tcpSocket:
            port: 80
  traffic:
  - latestRevision: true # <<< SOLUTION FOR ISSUE B
    percent: 100