apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend-service
  labels: # Keep your Cloud Deploy labels (these are important for Cloud Deploy to manage the service)
    delivery-pipeline-id: actionable-iq-pipeline
    location: us-east5
    managed-by: google-cloud-deploy
    project-id: actionableiq
    target-id: backend-staging
spec:
  template:
    spec:
      serviceAccountName: backend-service-runner@actionableiq.iam.gserviceaccount.com # Use your runtime Service Account
      containers:
      - image: backend-image # Skaffold will replace this via the --images flag from your cloudbuild.yaml
        ports:
        - name: http1 # Knative requires the port to be named (usually http1 or h2c)
          containerPort: 8080 # The port your application listens on
        env:
        # Only the most basic environment variables needed for an ASP.NET Core app to start
        # without immediately crashing due to missing fundamental configuration.
        # Your app might not be "functional" but the Cloud Run revision should be created.
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ASPNETCORE_ENVIRONMENT
          value: "MinimalTest" # Or "Staging", but "MinimalTest" makes it clear this is a specific test config
        #
        # NO other application-specific environment variables (e.g., Mailgun, JWT, Database, Google Auth)
        # NO valueFrom secretKeyRef sections
        #
        # NO startupProbe for this test (to remove another variable and rely on Cloud Run's default checks)
        #
        resources: # You can keep or remove/comment out resources for this test; keeping them is fine.
          limits:
            cpu: 2000m
            memory: 4Gi
  traffic:
  - latestRevision: true
    percent: 100