apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend-service
  labels:
spec:
  template:
    metadata:
    spec:
      serviceAccountName: 788583965739-compute@developer.gserviceaccount.com
      containers:
      - image: backend-image
        ports:
        - name: http1
          containerPort: 8080
        env:
          - name: ASPNETCORE_URLS
            value: http://+:8080
          - name: MAILGUN_API_KEY
            valueFrom:
              secretKeyRef:
                name: mailgun-api-key
                key: latest # Corrected
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: actionableiq-db-connection-string
                key: latest # Corrected
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        startupProbe:
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 15
          failureThreshold: 24
          tcpSocket:
            port: 8080
  traffic:
  - latestRevision: true
    percent: 100