# actionable-iq/delivery-pipeline.yaml
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: actionable-iq-pipeline
description: Frontend and Backend deployment pipeline
serialPipeline:
  stages:
    # --- Staging Stage ---
    - targetId: frontend-staging
      profiles:
        - stagingFrontend # Must match a profile name in skaffold.yaml
    - targetId: backend-staging
      profiles:
        - stagingBackend  # Must match a profile name in skaffold.yaml
    # --- Production Stage ---
    - targetId: frontend-prod
      profiles:
        - productionFrontend # Must match a profile name in skaffold.yaml
    - targetId: backend-prod
      profiles:
        - productionBackend  # Must match a profile name in skaffold.yaml