# actionable-iq/delivery-pipeline.yaml
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: actionable-iq-pipeline # Name of the pipeline
description: Frontend and Backend deployment pipeline
serialPipeline: # Defines stages that run sequentially
  stages:
    # --- Staging Stage ---
    - targetId: frontend-staging # First target in this stage
      profiles: # Skaffold profiles to use for this stage
        - staging-frontend # MODIFIED
    - targetId: backend-staging  # Second target in this stage
      profiles: # Skaffold profiles to use for this stage
        - staging-backend # MODIFIED
    # --- Production Stage ---
    # This stage runs only after the Staging stage is complete and the release is promoted
    - targetId: frontend-prod # First target in the production stage
      profiles:
        - production-frontend # MODIFIED
    - targetId: backend-prod  # Second target in the production stage
      profiles:
        - production-backend # MODIFIED