apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    delivery-pipeline-id: actionable-iq-pipeline
    location: us-east5
    managed-by: google-cloud-deploy
    project-id: actionableiq
    # release-id: rel-1037908 # Skaffold/Cloud Deploy might manage this
    target-id: frontend-staging
  name: frontend-service
spec:
  template:
    metadata:
      # You can add annotations here if needed in the future
      # annotations:
      #   autoscaling.knative.dev/maxScale: "40" # Example from your previous full YAML
    spec:
      containers:
      - image: us-east5-docker.pkg.dev/actionableiq/frontend-repo/frontend-app # Let Skaffold/Cloud Build inject the tag/digest
        env:
        - name: REACT_APP_API_URL
          value: https://placeholder.example.com/api # Correctly placed value
        ports:
        - containerPort: 80
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15 # Optional: Give a few seconds for httpd to start
          timeoutSeconds: 5
          periodSeconds: 10 # How often to probe after initial success/failure
          failureThreshold: 24 # How many failures before giving up
  traffic:
  - latestRevision: true # Route traffic to the latest healthy revision
    percent: 100