apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  # Name of the Cloud Run service for the frontend
  name: frontend-service
  # Optional: Add annotations for things like ingress control or CPU allocation
  # annotations:
  #   run.googleapis.com/ingress: all # Allow public access
spec:
  template:
    metadata:
      # Optional: Annotations specific to the revision
      # annotations:
      #   autoscaling.knative.dev/maxScale: '5' # Example: Limit max instances
    spec:
      # Set the service account the revision runs as (defaults to Compute Engine default SA)
      # serviceAccountName: YOUR_PROJECT_NUMBER-compute@developer.gserviceaccount.com
      containers:
        # The 'image' field will be automatically replaced by Skaffold/Cloud Deploy
        # based on the '--images' flag passed to 'gcloud deploy releases create'
      - image: frontend-image # Do not change this placeholder manually
        ports:
          # Port exposed by Nginx in the frontend Docker container
        - containerPort: 80
        # Optional: Define environment variables for the frontend container
        # Example: If you need to configure API URL at runtime instead of build time
        env:
        - name: REACT_APP_API_URL
        value: "https://placeholder.example.com/api" # Will be patched by Skaffold profiles
        resources:
          # Define resource limits (adjust as needed)
          limits:
            cpu: "1000m" # 1 vCPU
            memory: "256Mi"