    # actionable-iq/skaffold.yaml
    apiVersion: skaffold/v4beta7
    kind: Config
    metadata:
      name: actionable-iq-deployment

    build:
      artifacts:
        - image: frontend-image # Use simple key
        - image: backend-image  # Use simple key
      googleCloudBuild:
        projectId: $PROJECT_ID

    deploy:
      cloudrun: {}
      # NO global manifests section needed here

    profiles:
      - name: stagingFrontend # Specific name
        manifests:
          rawYaml:
            - service-frontend-staging.yaml # ONLY frontend staging manifest

      - name: stagingBackend # Specific name
        manifests:
          rawYaml:
            - service-backend-staging.yaml  # ONLY backend staging manifest

      - name: productionFrontend # Specific name
        manifests:
          rawYaml:
            - service-frontend-prod.yaml # ONLY frontend prod manifest

      - name: productionBackend # Specific name
        manifests:
          rawYaml:
            - service-backend-prod.yaml  # ONLY backend prod manifest