apiVersion: skaffold/v4beta12 # Or your current Skaffold version
kind: Config
metadata:
  name: actionable-iq-pipeline-config # Renamed for clarity
build:
  artifacts:
    - image: frontend-image
      context: actionable-iq/client # Context specific to frontend
      docker:
        dockerfile: Dockerfile # This will be actionable-iq/client/Dockerfile
    - image: backend-image
      context: actionable-iq/server # Context specific to backend
      docker:
        dockerfile: Dockerfile # This will be actionable-iq/server/Dockerfile
  tagPolicy:
    gitCommit: {} # This tags images with the git commit SHA
  googleCloudBuild:
    projectId: actionableiq # Make sure this is your project ID
    # Add other GCB settings if needed (e.g., machineType)
manifests:
  rawYaml:
    - actionable-iq/service-frontend-staging.yaml # Path to your frontend service manifest
    - actionable-iq/service-backend-staging.yaml # <<< ADD PATH TO YOUR BACKEND SERVICE MANIFEST
deploy:
  cloudrun: {} # Indicates deployment to Cloud Run, Skaffold will use gcloud commands
  # Or if using kubectlDeploy for Knative manifests directly:
  # kubectl: {}
  logs:
    prefix: container