apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: actionable-iq-pipeline-config
# build:
#   artifacts:
#     - image: frontend-image
#       context: actionable-iq/client
#       docker:
#         dockerfile: Dockerfile
#     - image: backend-image
#       context: actionable-iq/server
#       docker:
#         dockerfile: Dockerfile
#   tagPolicy:
#     gitCommit: {}
#   googleCloudBuild:
#     projectId: actionableiq

# --- DEFAULT MANIFESTS (can be empty if all are profile-specific) ---
manifests:
  rawYaml: [] # No default manifests, all are profile-specific

# --- PROFILES SECTION ---
profiles:
  - name: stagingFrontend
    manifests:
      rawYaml:
        - client/service-frontend-staging.yaml # Path to your frontend STAGING service manifest
  - name: stagingBackend
    manifests:
      rawYaml:
        - server/service-backend-staging.yaml     # Path to your backend STAGING service manifest
  - name: productionFrontend
    manifests:
      rawYaml:
        - client/service-frontend-prod.yaml # Path to your frontend PRODUCTION service manifest
  - name: productionBackend
    manifests:
      rawYaml:
        - server/service-backend-prod.yaml     # Path to your backend PRODUCTION service manifest

deploy:
  cloudrun: {} # Global deploy configuration, can be overridden in profiles if needed
  logs:
    prefix: container