# actionable-iq/skaffold.yaml
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: actionable-iq-deployment

# YOUR EXISTING BUILD SECTION (Should be fine)
build:
  artifacts:
    - image: ${_REGION}-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend-app
      context: client
    - image: ${_REGION}-docker.pkg.dev/$PROJECT_ID/backend-repo/backend-app
      context: server
  googleCloudBuild:
    projectId: $PROJECT_ID

# YOUR EXISTING DEPLOY SECTION (Should be fine)
deploy:
  cloudrun: {}

# Base manifests - Skaffold needs to know about them globally
manifests:
  rawYaml:
    - service-frontend.yaml
    - service-backend.yaml

# NEW PROFILES SECTION (Replace your old profiles section with this)
profiles:
  # --- Staging Profiles ---
  - name: stagingFrontend # Profile specifically for staging frontend
    manifests:
      rawYaml:
        - service-frontend.yaml # Only this manifest
    patches:
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value # For REACT_APP_API_URL
        value: "https://staging-backend-service-url" # Replace with actual URL later

  - name: stagingBackend # Profile specifically for staging backend
    manifests:
      rawYaml:
        - service-backend.yaml # Only this manifest
    patches:
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value # For ASPNETCORE_ENVIRONMENT
        value: "Staging"

  # --- Production Profiles ---
  - name: productionFrontend # Profile specifically for production frontend
    manifests:
      rawYaml:
        - service-frontend.yaml # Only this manifest
    patches:
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value # For REACT_APP_API_URL
        value: "https://production-backend-service-url" # Replace with actual URL later

  - name: productionBackend # Profile specifically for production backend
    manifests:
      rawYaml:
        - service-backend.yaml # Only this manifest
    patches:
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value # For ASPNETCORE_ENVIRONMENT
        value: "Production"