# actionable-iq/skaffold.yaml
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: actionable-iq-deployment

build:
  artifacts:
    - image: frontend-image
      context: client
    - image: backend-image
      context: server
  googleCloudBuild:
    projectId: $PROJECT_ID

deploy:
  cloudrun: {}
  # No global manifests needed if all are profile-specific

profiles:
  - name: staging
    manifests:
      rawYaml:
        - service-frontend-staging.yaml # Specific to staging
        - service-backend-staging.yaml  # Specific to staging
    # No patches needed if values are set directly in these files

  - name: production
    manifests:
      rawYaml:
        - service-frontend-prod.yaml # Specific to prod
        - service-backend-prod.yaml  # Specific to prod
    # No patches needed